name: sync main for develop

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *" # run at 4 AM JST

jobs:
  sync-main-for-develop:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        uses: tier4/github-actions/create-sync-main-pull-request@main
        id: create-pull-request
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: develop
          main-branch: main
          sync-branch: sync-main-for-develop

      - name: Enable Auto-merge
        if: steps.create-pull-request.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          pull-request-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
          merge-method: merge
